# Generated by Django 4.2.13 on 2026-05-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Membro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("cargo", models.CharField(max_length=255)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("presidencia", "Presidência"),
                            ("diretoria", "Diretoria"),
                            ("coordenacao", "Coordenação"),
                            ("equipe", "Equipe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("semestre", models.CharField(help_text="e.g. 2024.1", max_length=10)),
                ("foto", models.ImageField(upload_to="membros/")),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("ordem", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["ordem"],
            },
        ),
    ]
