# Generated by Django 4.2.13 on 2026-05-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membros", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membro",
            name="alumni",
            field=models.BooleanField(default=False),
        ),
    ]
