# Generated by Django 4.2.13 on 2026-05-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membros", "0002_membro_alumni"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membro",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("presidencia", "Presidência"),
                    ("diretoria", "Diretoria"),
                    ("coordenacao", "Coordenação"),
                    ("equipe", "Equipe"),
                    ("trainee", "Trainee"),
                ],
                max_length=20,
            ),
        ),
    ]
