# Generated by Django 4.2.13 on 2026-05-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("data", models.DateField()),
                ("imagem", models.ImageField(upload_to="eventos/")),
                ("link", models.URLField(blank=True)),
                (
                    "destaque",
                    models.BooleanField(
                        default=False, help_text="Show as featured event"
                    ),
                ),
                (
                    "passado",
                    models.BooleanField(default=False, help_text="Mark as past event"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
    ]
