# Generated by Django 4.2.13 on 2026-05-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="palestrante",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="evento",
            name="subtitulo",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
