# Generated by Django 4.2.13 on 2026-05-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("url", models.URLField()),
                (
                    "secao",
                    models.CharField(
                        choices=[
                            ("material", "Material Próprio"),
                            ("cursos", "Cursos Recomendados"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("iniciante", "Iniciante"),
                            ("intermediario", "Intermediário"),
                            ("avancado", "Avançado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("autor", models.CharField(blank=True, max_length=255)),
                ("data", models.DateField(blank=True, null=True)),
                ("ordem", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["ordem"],
            },
        ),
    ]
