# Generated by Django 4.2.13 on 2026-05-12 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessoSeletivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("fechado", "Fechado"),
                            ("em_breve", "Em Breve"),
                        ],
                        default="em_breve",
                        max_length=20,
                    ),
                ),
                (
                    "proxima_edicao",
                    models.CharField(help_text="e.g. 2026.2", max_length=50),
                ),
                ("url_inscricao", models.URLField(blank=True)),
                (
                    "texto_cta",
                    models.CharField(
                        default="Faça parte de uma equipe que constrói o futuro da Inteligência Artificial no Brasil.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Processo Seletivo",
            },
        ),
        migrations.CreateModel(
            name="EtapaProcessoSeletivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("ativa", models.BooleanField(default=True)),
                (
                    "processo_seletivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapas",
                        to="processo_seletivo.processoseletivo",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem"],
            },
        ),
    ]
