# Generated by Django 5.2.14 on 2026-05-13 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processo_seletivo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CriterioProcessoSeletivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        help_text="lucide-react icon name, e.g. Lightbulb",
                        max_length=64,
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("ativa", models.BooleanField(default=True)),
                (
                    "processo_seletivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterios",
                        to="processo_seletivo.processoseletivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Critério",
                "verbose_name_plural": "Critérios",
                "ordering": ["ordem"],
            },
        ),
    ]
