# Generated by Django 4.2.13 on 2026-05-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artigo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("resumo", models.TextField()),
                (
                    "setor",
                    models.CharField(
                        choices=[
                            ("engenharia", "Engenharia"),
                            ("direito", "Direito"),
                            ("financas", "Finanças"),
                        ],
                        max_length=20,
                    ),
                ),
                ("edicao", models.CharField(help_text="e.g. Ed. 3", max_length=50)),
                (
                    "destaque",
                    models.BooleanField(
                        default=False, help_text="Featured article in this sector"
                    ),
                ),
                ("publicado_em", models.DateField()),
            ],
            options={
                "ordering": ["-publicado_em"],
            },
        ),
        migrations.CreateModel(
            name="Inscricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "setor",
                    models.CharField(
                        choices=[
                            ("engenharia", "Engenharia"),
                            ("direito", "Direito"),
                            ("financas", "Finanças"),
                        ],
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
    ]
