# Generated by Django 5.2.14 on 2026-05-13 02:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artigo",
            options={"ordering": ["-edicao__ano", "-edicao__mes", "setor"]},
        ),
        migrations.RemoveField(
            model_name="artigo",
            name="publicado_em",
        ),
        migrations.AddField(
            model_name="artigo",
            name="fonte",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artigo",
            name="url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name="Edicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                (
                    "mes",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("ano", models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ["-ano", "-mes", "-numero"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("numero", "mes", "ano"),
                        name="unique_edicao_numero_mes_ano",
                    )
                ],
            },
        ),
        migrations.AlterField(
            model_name="artigo",
            name="edicao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artigos",
                to="newsletter.edicao",
            ),
        ),
    ]
