# Generated by Django 5.2.14 on 2026-05-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0002_alter_artigo_options_remove_artigo_publicado_em_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="inscricao",
            constraint=models.UniqueConstraint(
                fields=("email", "setor"), name="unique_inscricao_email_setor"
            ),
        ),
    ]
