# Generated by Django 4.2.13 on 2026-05-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Depoimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autor", models.CharField(max_length=255)),
                ("cargo", models.CharField(max_length=255)),
                ("texto", models.TextField()),
                ("foto", models.ImageField(blank=True, upload_to="depoimentos/")),
            ],
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pergunta", models.CharField(max_length=500)),
                ("resposta", models.TextField()),
                ("ordem", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="Parceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("logo", models.ImageField(upload_to="parceiros/")),
                ("url", models.URLField(blank=True)),
                ("ordem", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(help_text="Public display email", max_length=255),
                ),
                (
                    "contact_recipient_email",
                    models.EmailField(
                        help_text="Where contact form submissions are sent",
                        max_length=254,
                    ),
                ),
                ("instagram_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("endereco", models.TextField(blank=True)),
                ("google_maps_embed_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
