# Generated by Django 4.2.13 on 2026-05-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="depoimento",
            options={"ordering": ["ordem"]},
        ),
        migrations.AddField(
            model_name="depoimento",
            name="ordem",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="email",
            field=models.EmailField(help_text="Public display email", max_length=254),
        ),
    ]
