# Generated by Django 4.2.13 on 2026-05-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_depoimento_options_depoimento_ordem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="github_url",
            field=models.URLField(blank=True),
        ),
    ]
