# Generated by Django 4.2.13 on 2026-05-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_sitesettings_google_maps_embed_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("titulo", models.CharField(max_length=200)),
                ("texto", models.TextField()),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "posicao",
                    models.CharField(
                        choices=[
                            ("apos_missao", "Após Missão"),
                            ("apos_valores", "Após Valores"),
                            ("apos_stats", "Após Stats"),
                            ("apos_depoimentos", "Após Depoimentos"),
                            ("apos_parceiros", "Após Parceiros"),
                            ("apos_historia", "Após História"),
                        ],
                        default="apos_missao",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloco de conteúdo (Sobre)",
                "verbose_name_plural": "Blocos de conteúdo (Sobre)",
                "ordering": ["posicao", "ordem"],
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.PositiveIntegerField()),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("ordem", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Marco histórico",
                "verbose_name_plural": "Marcos históricos",
                "ordering": ["ano", "ordem"],
            },
        ),
        migrations.CreateModel(
            name="SobreContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_eyebrow", models.CharField(default="SOBRE NÓS", max_length=120)),
                (
                    "hero_quote",
                    models.TextField(
                        help_text="Frase-manifesto exibida no topo da página /sobre"
                    ),
                ),
                ("hero_attribution", models.CharField(blank=True, max_length=255)),
                ("missao", models.TextField(help_text="Parágrafo da seção Missão")),
                (
                    "applicants_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total de inscritos no último processo seletivo",
                    ),
                ),
                (
                    "projects_delivered",
                    models.PositiveIntegerField(
                        blank=True, help_text="Projetos entregues (opcional)", null=True
                    ),
                ),
                (
                    "founding_year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Ano de fundação da organização",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sobre — Conteúdo",
                "verbose_name_plural": "Sobre — Conteúdo",
            },
        ),
        migrations.CreateModel(
            name="Valor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=120)),
                ("descricao", models.TextField()),
                ("ordem", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Valor",
                "verbose_name_plural": "Valores",
                "ordering": ["ordem"],
            },
        ),
    ]
