# Generated by Django 4.2.13 on 2026-05-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_seed_sobre_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="foto",
            field=models.ImageField(blank=True, upload_to="milestones/"),
        ),
        migrations.AddField(
            model_name="sobrecontent",
            name="headline",
            field=models.CharField(
                blank=True,
                help_text="Título da seção Quem Somos (ex: 'A comunidade de IA do Insper')",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="sobrecontent",
            name="semester",
            field=models.CharField(
                default="2026.1",
                help_text="Semestre exibido no título da seção Stats (ex: '2026.1')",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="contentblock",
            name="posicao",
            field=models.CharField(
                choices=[
                    ("apos_quem_somos", "Após Quem Somos"),
                    ("apos_stats", "Após Stats"),
                    ("apos_eventos", "Após Eventos"),
                    ("apos_valores", "Após Valores"),
                    ("apos_historia", "Após História"),
                    ("apos_missao", "Após Missão (legado)"),
                    ("apos_depoimentos", "Após Depoimentos (legado)"),
                    ("apos_parceiros", "Após Parceiros (legado)"),
                ],
                default="apos_quem_somos",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="sobrecontent",
            name="missao",
            field=models.TextField(
                help_text="Parágrafo da seção Quem Somos (combina quem somos + missão)"
            ),
        ),
    ]
