# Generated by Django 4.2.13 on 2026-05-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_seed_redesign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parceiro",
            name="logo",
            field=models.ImageField(blank=True, upload_to="parceiros/"),
        ),
    ]
