# Generated by Django 4.2.13 on 2026-05-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_seed_placeholder_parceiros"),
    ]

    operations = [
        migrations.AddField(
            model_name="parceiro",
            name="descricao",
            field=models.TextField(
                blank=True, help_text="Texto exibido ao passar o mouse no card"
            ),
        ),
    ]
